version: "2"

services:
  mysql:
    image: mysql:5.7.22
    ports:
      - 3306:3306/tcp
    environment:
      - MYSQL_ROOT_PASSWORD=loopedge-secret!
      - MYSQL_DATABASE=dbtest
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=loopedge-secret!
    restart: 'no'
    volumes:
      - mysqldb-vol:/var/lib/mysql 

volumes:
  mysqldb-vol:
