minio:
  image: minio/minio
  volumes:
   - minio-vol:/data
  ports:
   - "${MINIO_PORT}:9000"
  environment:
   MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
   MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  command: server /data
