elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
  container_name: elasticsearch
  environment:
    - cluster.name=docker-cluster
    - discovery.type=single-node
  volumes:
    - elasticsearch-vol:/usr/share/elasticsearch/data
  ports:
    - ${ES_PORT}:9200

