version: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
    volumes:
      - elasticsearch-vol:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
      - 9300:9300

volumes:
  elasticsearch-vol: