name: ScadaLTS
description: Scada-LTS is an Open Source, web-based, multi-platform solution for building your own SCADA (Supervisory Control and Data Acquisiton) system.
category: Utils
version: latest
